# Generated by Django 3.2.4 on 2021-06-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(default='United Kingdom (UK)', max_length=100)),
                ('Street_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('Phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
