# Generated by Django 3.2.4 on 2021-08-10 12:36

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='My_DivanBeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='divanbeds', max_length=50, null=True)),
                ('Description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='My_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('2FT 6', '2FT 6"-small'), ('3FT', '3FT-single'), ('4FT', '4FT-Small-double'), ('4FT 6', '4FT 6"-Double'), ('5FT', '5FT-king'), ('6FT', '6FT-super-king'), ('extra', 'extra'), ('extra', 'extra')], max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('color', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('grey linen', 'grey linen'), ('grey seude ', 'grey seude'), ('charcoal chenille', 'charcoal chenille'), ('black crushed velvet', 'black crushed velvet')], max_length=61, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.my_divanbeds')),
            ],
        ),
        migrations.CreateModel(
            name='My_Mattress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mattaress_type', models.CharField(choices=[('No Mattress', 'No Mattress'), ('Orthopedic Mattress', 'Orthopedic Mattress'), ('1500 Pocket Pillow Top Mattress', '1500 Pocket Pillow Top Mattress'), ('1500 Pocket (tinsel Top)', '1500 Pocket (tinsel Top)')], max_length=500)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('color', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('grey linen', 'grey linen'), ('grey seude ', 'grey seude'), ('charcoal chenille', 'charcoal chenille'), ('black crushed velvet', 'black crushed velvet')], max_length=61, null=True)),
                ('size', models.ForeignKey(default='No Mattress', on_delete=django.db.models.deletion.CASCADE, to='Test.my_variant')),
            ],
        ),
        migrations.CreateModel(
            name='My_Headboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('No Headboard', 'No Headboard'), ('26 Inch Diamond Button Cube Headboard', '26 Inch Diamond Button Cube Headboard'), ('26 Inch Matching Button Cube Headboard', '26 Inch Matching Button Cube Headboard'), ('48 Inch Floor Standing Diamond Cube Headboard', '48 Inch Floor Standing Diamond Cube Headboard'), ('48 Inch Floor Standing Matching Button Cube Headboard', '48 Inch Floor Standing Matching Button Cube Headboard')], max_length=300, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('color', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('grey linen', 'grey linen'), ('grey seude ', 'grey seude'), ('charcoal chenille', 'charcoal chenille'), ('black crushed velvet', 'black crushed velvet')], max_length=61, null=True)),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.my_variant')),
            ],
        ),
        migrations.CreateModel(
            name='My_FeetCastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('free Caster wheel', 'free Caster wheel'), ('chrome Gliders ', 'Chrome Gliders')], max_length=200)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.my_variant')),
            ],
        ),
        migrations.CreateModel(
            name='My_Drawers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('no-drawers', 'no-drawers'), ('Two Drawer Same Side', 'Two Drawer Same Side'), ('Two-Drawer Foot end', 'wo-Drawer Foot end'), ('4 Drawers', '4 Drawers')], max_length=200)),
                ('color', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('grey linen', 'grey linen'), ('grey seude ', 'grey seude'), ('charcoal chenille', 'charcoal chenille'), ('black crushed velvet', 'black crushed velvet')], max_length=61, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('size', models.ForeignKey(default='no Drawer', on_delete=django.db.models.deletion.CASCADE, to='Test.my_variant')),
            ],
        ),
    ]
